/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/AppLayout.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    CompleteHousekeepingTaskDialog: typeof import('./src/components/CompleteHousekeepingTaskDialog.vue')['default']
    CreateMaintenanceTicketDialog: typeof import('./src/components/CreateMaintenanceTicketDialog.vue')['default']
    EmptyState: typeof import('./src/components/states/EmptyState.vue')['default']
    ErrorState: typeof import('./src/components/states/ErrorState.vue')['default']
    GuestRequestDialog: typeof import('./src/components/GuestRequestDialog.vue')['default']
    GuestRequestFormDialog: typeof import('./src/components/GuestRequestFormDialog.vue')['default']
    HousekeepingTaskDialog: typeof import('./src/components/HousekeepingTaskDialog.vue')['default']
    InspectHousekeepingTaskDialog: typeof import('./src/components/InspectHousekeepingTaskDialog.vue')['default']
    LanguageSwitcher: typeof import('./src/components/LanguageSwitcher.vue')['default']
    LoadingState: typeof import('./src/components/states/LoadingState.vue')['default']
    MaintenanceTicketDialog: typeof import('./src/components/MaintenanceTicketDialog.vue')['default']
    NightAuditCloseDialog: typeof import('./src/components/NightAuditCloseDialog.vue')['default']
    NightAuditExceptionDialog: typeof import('./src/components/NightAuditExceptionDialog.vue')['default']
    NightAuditReopenDialog: typeof import('./src/components/NightAuditReopenDialog.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    PermissionDenied: typeof import('./src/components/states/PermissionDenied.vue')['default']
    PostAdjustmentDialog: typeof import('./src/components/PostAdjustmentDialog.vue')['default']
    PostChargeDialog: typeof import('./src/components/PostChargeDialog.vue')['default']
    PostPaymentDialog: typeof import('./src/components/PostPaymentDialog.vue')['default']
    PropertySelector: typeof import('./src/components/PropertySelector.vue')['default']
    RoomDetailDialog: typeof import('./src/components/RoomDetailDialog.vue')['default']
    RoomStatusBadge: typeof import('./src/components/RoomStatusBadge.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceRecoveryDialog: typeof import('./src/components/ServiceRecoveryDialog.vue')['default']
    SplitFolioDialog: typeof import('./src/components/SplitFolioDialog.vue')['default']
    StateMessage: typeof import('./src/components/states/StateMessage.vue')['default']
    TakeOutOfServiceDialog: typeof import('./src/components/TakeOutOfServiceDialog.vue')['default']
    VerifyMaintenanceDialog: typeof import('./src/components/VerifyMaintenanceDialog.vue')['default']
  }
}
