/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddStayNoteDialog: typeof import('./src/components/AddStayNoteDialog.vue')['default']
    AppLayout: typeof import('./src/components/AppLayout.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    ArrivalsPanel: typeof import('./src/components/dashboard/ArrivalsPanel.vue')['default']
    AssignRoomDialog: typeof import('./src/components/AssignRoomDialog.vue')['default']
    ChangeRoomDialog: typeof import('./src/components/ChangeRoomDialog.vue')['default']
    CompleteHousekeepingTaskDialog: typeof import('./src/components/CompleteHousekeepingTaskDialog.vue')['default']
    CreateMaintenanceTicketDialog: typeof import('./src/components/CreateMaintenanceTicketDialog.vue')['default']
    CreateRoomServiceOrderDialog: typeof import('./src/components/CreateRoomServiceOrderDialog.vue')['default']
    DashboardCard: typeof import('./src/components/dashboard/DashboardCard.vue')['default']
    DeparturesPanel: typeof import('./src/components/dashboard/DeparturesPanel.vue')['default']
    DonutChart: typeof import('./src/components/dashboard/DonutChart.vue')['default']
    EmptyState: typeof import('./src/components/states/EmptyState.vue')['default']
    ErrorState: typeof import('./src/components/states/ErrorState.vue')['default']
    ExtendStayDialog: typeof import('./src/components/ExtendStayDialog.vue')['default']
    GuestDuplicateDialog: typeof import('./src/components/GuestDuplicateDialog.vue')['default']
    GuestForm: typeof import('./src/components/GuestForm.vue')['default']
    GuestRequestDialog: typeof import('./src/components/GuestRequestDialog.vue')['default']
    GuestRequestFormDialog: typeof import('./src/components/GuestRequestFormDialog.vue')['default']
    HousekeepingTaskDialog: typeof import('./src/components/HousekeepingTaskDialog.vue')['default']
    InspectHousekeepingTaskDialog: typeof import('./src/components/InspectHousekeepingTaskDialog.vue')['default']
    KpiCard: typeof import('./src/components/dashboard/KpiCard.vue')['default']
    LanguageSwitcher: typeof import('./src/components/LanguageSwitcher.vue')['default']
    LoadingState: typeof import('./src/components/states/LoadingState.vue')['default']
    MaintenanceTicketDialog: typeof import('./src/components/MaintenanceTicketDialog.vue')['default']
    MiniBars: typeof import('./src/components/dashboard/MiniBars.vue')['default']
    NightAuditCard: typeof import('./src/components/dashboard/NightAuditCard.vue')['default']
    NightAuditCloseDialog: typeof import('./src/components/NightAuditCloseDialog.vue')['default']
    NightAuditExceptionDialog: typeof import('./src/components/NightAuditExceptionDialog.vue')['default']
    NightAuditReopenDialog: typeof import('./src/components/NightAuditReopenDialog.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    PermissionDenied: typeof import('./src/components/states/PermissionDenied.vue')['default']
    PostAdjustmentDialog: typeof import('./src/components/PostAdjustmentDialog.vue')['default']
    PostChargeDialog: typeof import('./src/components/PostChargeDialog.vue')['default']
    PostPaymentDialog: typeof import('./src/components/PostPaymentDialog.vue')['default']
    PropertySelector: typeof import('./src/components/PropertySelector.vue')['default']
    RoomDetailDialog: typeof import('./src/components/RoomDetailDialog.vue')['default']
    RoomServiceOrderDialog: typeof import('./src/components/RoomServiceOrderDialog.vue')['default']
    RoomStatusBadge: typeof import('./src/components/RoomStatusBadge.vue')['default']
    RoomStatusBoard: typeof import('./src/components/dashboard/RoomStatusBoard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceRecoveryDialog: typeof import('./src/components/ServiceRecoveryDialog.vue')['default']
    ShortenStayDialog: typeof import('./src/components/ShortenStayDialog.vue')['default']
    SourceMixCard: typeof import('./src/components/dashboard/SourceMixCard.vue')['default']
    SplitFolioDialog: typeof import('./src/components/SplitFolioDialog.vue')['default']
    StateMessage: typeof import('./src/components/states/StateMessage.vue')['default']
    StatTile: typeof import('./src/components/dashboard/StatTile.vue')['default']
    TakeOutOfServiceDialog: typeof import('./src/components/TakeOutOfServiceDialog.vue')['default']
    VerifyMaintenanceDialog: typeof import('./src/components/VerifyMaintenanceDialog.vue')['default']
    WalkInStepper: typeof import('./src/components/WalkInStepper.vue')['default']
  }
}
