/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/AppLayout.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    EmptyState: typeof import('./src/components/states/EmptyState.vue')['default']
    ErrorState: typeof import('./src/components/states/ErrorState.vue')['default']
    LanguageSwitcher: typeof import('./src/components/LanguageSwitcher.vue')['default']
    LoadingState: typeof import('./src/components/states/LoadingState.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    PermissionDenied: typeof import('./src/components/states/PermissionDenied.vue')['default']
    PropertySelector: typeof import('./src/components/PropertySelector.vue')['default']
    RoomDetailDialog: typeof import('./src/components/RoomDetailDialog.vue')['default']
    RoomStatusBadge: typeof import('./src/components/RoomStatusBadge.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StateMessage: typeof import('./src/components/states/StateMessage.vue')['default']
  }
}
