"""Server context for the Vue operational frontend served at /pms.

`pms.html` is generated by the Vite build (see frontend/vite.config.js) and is
overwritten on every build, so all server-side behaviour lives here.
"""

import frappe

no_cache = 1


def get_context(context):
	"""Authenticate the shell and hand it the boot data it needs."""
	if frappe.session.user == "Guest":
		frappe.local.flags.redirect_location = "/login?redirect-to=/pms"
		raise frappe.Redirect

	csrf_token = frappe.sessions.get_csrf_token()
	frappe.db.commit()  # nosemgrep: the CSRF token must survive this request

	context.csrf_token = csrf_token

	# Each key is assigned to `window[key]` by the build's boot script.
	context.boot = {
		"csrf_token": csrf_token,
		"site_name": frappe.local.site,
		"sitename": frappe.local.site,
		"pms_boot": {
			"user": frappe.session.user,
			"app_version": frappe.get_attr("hospitality_pms.__version__"),
		},
	}

	return context
